services:
  bimbly-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_WS_URL: ${VITE_WS_URL}
    container_name: bimbly-frontend
    ports:
      - "81:80"
    restart: unless-stopped
    networks:
      - bimbly-network

networks:
  bimbly-network:
    external: true
